### ISSUE TITLE
Group results by rule to simplify output

### ISSUE THREAD

**Issue by Gby56** [azu/security-alert#15]
I already implemented this, and it's pretty good :)
I did a groupBy function on the ruleId in SARIF, and the markdown output now groups findings, same thing for suppressed results
This condenses the output in a better format for human reading, I think it's worth integrating by default
I'll make the PR for it, tell me what you think @azu

**Comment by azu** [comment]
Sweet!

I've merged PR and released https://github.com/azu/security-alert/releases/tag/v1.7.0
